import os


SONNET_MODEL = os.getenv("ANTHROPIC_SONNET_MODEL", "claude-sonnet-4-6")
HAIKU_MODEL = os.getenv("ANTHROPIC_HAIKU_MODEL", "claude-haiku-4-5-20251001")
MAX_COMPANY_NAME_LENGTH = 120
MAX_PRODUCT_DESCRIPTION_LENGTH = 2000